Mount hardening [skip ci]
nestybox/sysbox pull request #204
Opened 2021-02-08 20:46 UTC by rodnymolina

Testcase coverage for mount-hardening functionality.

The syscall interception testing-suite now looks like this ...

```
Executing basic mount syscall-interception tests ...
1..3
ok 1 mount path-resolution
ok 2 mount permission checking
ok 3 mount capability checking

Executing mount syscall-interception tests for procfs resources ...
1..27
ok 1 mount procfs
ok 2 mount procfs read-only
ok 3 mount procfs redudant
ok 4 procfs consistency
ok 5 procfs consistency 2
ok 6 procfs consistency (multiple syscont)
ok 7 procfs consistency (multiple procfs in multiple syscont)
ok 8 procfs remount
ok 9 mount procfs hidepid
ok 10 procfs remount submount
ok 11 procfs move mount
ok 12 procfs unmount
ok 13 procfs unmount submount
ok 14 procfs mount in inner container
ok 15 procfs mount in inner privileged container
ok 16 procfs mount in inner privileged container (ubuntu)
ok 17 # skip (FAILS (SYSBOX ISSUE #590)) unshare & mount procfs
ok 18 # skip (FAILS (SYSBOX ISSUE #590)) inner container unshare & mount procfs
ok 19 bind from procfs
ok 20 bind-to-self procfs submount
ok 21 bind over procfs submount
ok 22 bind from procfs base mount
ok 23 bind from procfs submount
ok 24 procfs private
ok 25 procfs shared
ok 26 procfs slave
ok 27 procfs unbindable

Executing mount syscall-interception tests for sysfs resources ...
1..23
ok 1 mount sysfs
ok 2 mount sysfs read-only
ok 3 mount sysfs redudant
ok 4 sysfs consistency
ok 5 sysfs consistency 2
ok 6 sysfs consistency (multiple syscont)
ok 7 sysfs consistency (multiple procfs in multiple syscont)
ok 8 sysfs remount
ok 9 sysfs mount & remount (superblock)
ok 10 /sys remount & mount (superblock)
ok 11 sysfs remount submount
ok 12 sysfs move mount
ok 13 sysfs unmount
ok 14 sysfs unmount submount
ok 15 bind from sysfs
ok 16 bind-to-self sysfs submount
ok 17 bind over sysfs submount
ok 18 bind from sysfs base mount
ok 19 bind from sysfs submount
ok 20 sysfs private
ok 21 sysfs shared
ok 22 sysfs slave
ok 23 sysfs unbindable

Executing mount syscall-interception tests for overlayfs resources ...
1..6
ok 1 mount overlayfs basic
ok 2 mount overlayfs addition ops
ok 3 mount overlayfs deletion ops
ok 4 mount overlayfs advanced ops
ok 5 mount overlayfs relative paths
ok 6 mount overlayfs multiple lower

Executing mount syscall-interception tests for immutable resources ...
1..13
ok 1 immutable mount can't be unmounted
ok 2 immutable ro mount can't be remounted rw
ok 3 immutable rw mount can be remounted ro
ok 4 immutable ro mount can be remounted ro
ok 5 immutable rw mount can be remounted rw
ok 6 immutable ro mount can't be bind-mounted rw
ok 7 immutable rw mount can be bind-mounted ro
ok 8 rw mount on top of immutable ro mount
ok 9 ro mount on top of immutable rw mount
ok 10 don't confuse inner priv container mount with immutable mount
ok 11 immutable null mount in inner mnt ns
ok 12 immutable null-new mount in inner mnt ns
ok 13 immutable tmpfs mount in inner mnt ns

Executing mount syscall-interception tests for immutable resources in chroot() ctx ...
1..11
ok 1 immutable mount can't be unmounted -- chroot()
ok 2 immutable ro mount can't be remounted rw -- chroot()
ok 3 immutable rw mount can be remounted ro -- chroot()
ok 4 immutable ro mount can be remounted ro -- chroot()
ok 5 immutable rw mount can be remounted rw -- chroot()
ok 6 immutable ro mount can't be bind-mounted rw -- chroot()
ok 7 immutable rw mount can be bind-mounted ro -- chroot()
ok 8 rw mount on top of immutable ro mount -- chroot()
ok 9 ro mount on top of immutable rw mount -- chroot()
ok 10 unmount chain of file bind-mounts -- chroot()
ok 11 unmount chain of dir bind-mounts -- chroot()

Executing mount syscall-interception tests for immutable resources in unshare() ctx ...
1..12
ok 1 immutable mount can't be unmounted -- unshare(mnt)
ok 2 immutable ro mount can't be remounted rw -- unshare(mnt)
ok 3 immutable rw mount can be remounted ro -- unshare(mnt)
ok 4 immutable ro mount can be remounted ro -- unshare(mnt)
ok 5 immutable rw mount can be remounted rw -- unshare(mnt)
ok 6 immutable ro mount can't be bind-mounted rw -- unshare(mnt)
ok 7 immutable rw mount can be bind-mounted ro -- unshare(mnt)
ok 8 rw mount on top of immutable ro mount -- unshare(mnt)
ok 9 ro mount on top of immutable rw mount -- unshare(mnt)
ok 10 unmount chain of file bind-mounts -- -- unshare(mnt)
ok 11 unmount chain of char bind-mounts -- unshare(mnt)
ok 12 unmount chain of dir bind-mounts -- unshare(mnt)

Executing mount syscall-interception tests for immutable resources in unshare() + chroot() ctx ...
1..11
ok 1 immutable mount can't be unmounted -- unshare(mnt) + chroot()
ok 2 immutable ro mount can't be remounted rw -- unshare(mnt) + chroot()
ok 3 immutable rw mount can be remounted ro -- unshare(mnt) + chroot()
ok 4 immutable ro mount can be remounted ro -- unshare(mnt) + chroot()
ok 5 immutable rw mount can be remounted rw -- unshare(mnt) + chroot()
ok 6 immutable ro mount can't be bind-mounted rw -- unshare(mnt) + chroot()
ok 7 immutable rw mount can be bind-mounted ro -- unshare(mnt) + chroot()
ok 8 rw mount on top of immutable ro mount -- unshare(mnt) + chroot()
ok 9 ro mount on top of immutable rw mount -- unshare(mnt) + chroot()
ok 10 unmount chain of file bind-mounts -- unshare(mnt) + chroot()
ok 11 unmount chain of dir bind-mounts -- unshare(mnt) + chroot()

Executing mount syscall-interception tests for immutable resources in unshare() + pivot() ctx ...
1..11
ok 1 immutable mount *can* be unmounted -- unshare(mnt) + pivot()
ok 2 immutable ro mount can't be remounted rw -- unshare(mnt) + pivot()
ok 3 immutable rw mount can be remounted ro -- unshare(mnt) + pivot()
ok 4 immutable ro mount can be remounted ro -- unshare(mnt) + pivot()
ok 5 immutable rw mount can be remounted rw -- unshare(mnt) + pivot()
ok 6 immutable ro mount can't be bind-mounted rw -- unshare(mnt) + pivot()
ok 7 immutable rw mount can be bind-mounted ro -- unshare(mnt) + pivot()
ok 8 rw mount on top of immutable ro mount -- unshare(mnt) + pivot()
ok 9 ro mount on top of immutable rw mount -- unshare(mnt) + pivot()
ok 10 unmount chain of file bind-mounts -- unshare(mnt) + pivot()
ok 11 unmount chain of dir bind-mounts -- unshare(mnt) + pivot()
```

2021-02-23 00:10 UTC, ctalledo commented on tests/helpers/mounts.bash
> +  #[ $(echo ${list} | tr " " "\n" | wc -l) -eq 0 ]
Remove this line.

2021-02-23 00:15 UTC, ctalledo commented on tests/helpers/mounts.bash
> +# Note that 'chroot' if-statements are not properly working and need tweaking.
Is this comment correct? if so, what's "not working properly"

2021-02-23 00:38 UTC, ctalledo commented on tests/syscall/mount/mount-immutables.bats
> +skipTest=0
Why do we need this variable?

We already have a "run_only_test <name>" function that we can add to `function setup()` to skip tests.

2021-02-23 00:40 UTC, ctalledo commented on tests/syscall/mount/mount-immutables.bats
> +  if [[ $skipTest -eq 1 ]]; then
I don't think we need this; same for all other tests.

2021-02-23 00:42 UTC, ctalledo commented on tests/helpers/mounts.bash
> +function empty_list() {
Suggestion: rename `empty_list()` -> `is_list_empty()` ? 

(otherwise it sounds like a statement that says "make this list empty").

2021-02-23 00:44 UTC, ctalledo commented on tests/syscall/mount/mount-immutables.bats
> +    [ "$status" -ne 0 ]
Should we check for a particular expected status here? (e.g., EPERM)

2021-02-23 00:47 UTC, ctalledo commented on tests/syscall/mount/mount-immutables.bats
> +
After remouting read-only, I would add a `docker exec ${syscont} sh -c "touch ${m}"` to verify the mount is indeed read-only (i.e., the touch will fail).

After remouting read-write, I would add a `docker exec ${syscont} sh -c "touch ${m}"` to verify the mount is indeed read-write (i.e., the touch will pass).

2021-02-23 00:48 UTC, ctalledo commented on tests/syscall/mount/mount-immutables.bats
> +    [ "$status" -ne 0 ]
I would add a `docker exec ${syscont} sh -c "touch ${m}"` to verify the mount continues to indeed be read-only (i.e., the touch will fail).

2021-02-23 00:49 UTC, ctalledo commented on tests/syscall/mount/mount-immutables.bats
> +# read-only inside the container.
Fix the comment: this test only remounts read-write.

2021-02-23 00:51 UTC, ctalledo commented on tests/syscall/mount/mount-immutables.bats
> +# to a new mountpoint then re-mounted read-write
Fix comment: 

" Ensure that a read-only immutable mount  can be bind-mounted to a new mountpoint, but not re-mounted read-write at the new mountpoint."

2021-02-23 00:51 UTC, ctalledo commented on tests/syscall/mount/mount-immutables.bats
> +    printf "\ntesting bind-mount of immutable ro bind-mount ${m} -> $target\n"
"testing remount of immutable ..."

2021-02-23 00:52 UTC, ctalledo commented on tests/syscall/mount/mount-immutables.bats
> +    printf "\ntesting bind-mount of immutable ro bind-mount ${m} -> $target\n"
Fix comment: "testing bind-mout of immutable mount"

2021-02-23 01:06 UTC, ctalledo commented on tests/syscall/mount/mount-immutables.bats
> +  docker exec ${syscont} sh -c "docker exec inner sh -c \"mount -o remount,bind,ro $linux_libmod_mount\""
I would add the corresponding `touch ${mnt}` checks after each of the mount steps.

2021-02-23 01:12 UTC, ctalledo commented on tests/syscall/mount/mount-immutables.bats
> +    # Create bind-mount and verify that only the first unmount is allowed.
Comment is incorrect, these are not bind mounts (they are overlapping / stacked mounts)

2021-02-23 01:15 UTC, ctalledo commented on tests/syscall/mount/mount-immutables.bats
> +@test "immutable tmpfs mount in inner mnt ns" {
I don't see the "inner mnt ns" in this test ...

2021-02-23 01:17 UTC, ctalledo commented on tests/syscall/mount/mount-immutables-unshare.bats
> +# an inner mount namespace, and then back to read-only.
Typo: "then back to read-write".

2021-02-23 01:18 UTC, ctalledo commented on tests/syscall/mount/mount-immutables-unshare.bats
> +    [ "$status" -eq 0 ]
Suggestion: add "touch" after each mount step to verify the mount is read-write or read-only.

2021-02-23 01:18 UTC, ctalledo commented on tests/syscall/mount/mount-immutables-unshare.bats
> +# read-only inside an inner mount namespace.
Typo: don't see the read-only part in the test.

2021-02-23 01:27 UTC, ctalledo commented on tests/syscall/mount/mount-immutables-unshare-pivot.bats
> +# Ensure immutable mounts can't be unmounted from inside the container
This test verifies something different: it verifies that within an L2 privileged container, the container can unmount all L2 mounts (even if those are bind-mounts from immutable mounts).

2021-02-23 01:28 UTC, ctalledo commented on tests/syscall/mount/mount-immutables-unshare-pivot.bats
> +# Ensure that a read-only immutable mount can't be remounted as read-write
This test verifies something different: it verifies that a **bind mount** from an immutable mount, exposed into an L2 container, can't be remounted read-write.

2021-02-23 01:29 UTC, ctalledo commented on tests/syscall/mount/mount-immutables-unshare-pivot.bats
> +# Ensure that a read-write immutable mount *can* be remounted as read-only inside
Same as before: this test applies to bind-mounts from immutable mounts, not to the original immutable mounts themselves.

2021-02-23 01:30 UTC, ctalledo commented on tests/syscall/mount/mount-immutables-unshare-pivot.bats
> +# the container, and then back to read-only.
"back to read-write".

2021-02-23 01:31 UTC, ctalledo commented on tests/syscall/mount/mount-immutables-unshare-pivot.bats
> +# read-only inside the container.
No read-only remount in this test.

2021-02-23 01:38 UTC, ctalledo commented on tests/syscall/mount/mount-immutables-unshare-chroot.bats
> +# Ensure immutable mounts can't be unmounted from inside an inner mount
This test is not operating on the immutable mounts, it's operating on bind mounts from the immutable mounts. To operate on the immutable mount directly, you have to chroot to a parent dir of the immutable mount (e.g., chroot to `/usr/src/` and unmount `linux-headers-...`).

I suspect the same applies to many of the tests below.

2021-02-23 01:40 UTC, ctalledo commented on tests/syscall/mount/mount-immutables-chroot.bats
> +# Ensure immutable mounts can't be unmounted from inside the container
This test is not operating on the immutable mounts, it's operating on bind mounts from the immutable mounts. To operate on the immutable mount directly, you have to chroot to a parent dir of the immutable mount (e.g., chroot to /usr/src/ and unmount linux-headers-...).

I suspect the same applies to many of the tests below.

2021-02-23 01:40 UTC, ctalledo requested changes
Tests look pretty good in general, though I found a few issues.

2021-02-25 06:05 UTC, rodnymolina reviewed
See my comments below.

2021-02-25 20:48 UTC, ctalledo approved these changes
Looks good, just a couple of suggestions.

2021-02-25 20:48 UTC, ctalledo commented on tests/syscall/mount/mount-immutables-chroot.bats
> +  run allow_immutable_unmounts
Would this work: `allow_immutable_mounts=$(unmounts_allowed)` 

(It's more concise)

Or alternatively:

```
run allow_immutable_unmounts
unmounts_allowed=$(status)
```

2021-02-25 20:48 UTC, ctalledo commented on tests/syscall/mount/mount-immutables-unshare-pivot.bats
> +    if [[ ${remounts_allowed} -eq 0 ]]; then
Would this work (is more concise)?

`[ "$status" -eq "$remounts_allowed ]`

2021-02-25 23:40 UTC, merged